// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.bigvalue.ai/
// Generated: 2026-06-17T07:01:05.523Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#e7e5e4' | '#0c0a09' | '#ffffff' | '#000000' | '#25252f' | '#3f3f49' | '#6867fe' | '#4434e2' | '#646371' | '#f5effe' | '#9291a5' | '#c299fb' | '#864fd4' | '#9e5df9' | '#64748b' | '#d4d3dd' | '#334155' | '#a8a7bb' | '#e8492a' | '#8d8dfb' | '#006746' | '#d2fbee' | '#00e49b' | '#dcdbfd' | '#3526c7' | '#1a1a1a' | '#565455';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Pretendard Variable';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700' | '800';

export type SpacingToken = '1px' | '48px' | '56px' | '73px' | '80px' | '100px' | '120px' | '148px' | '200px' | '223px' | '240px';

export type RadiusToken = '4px' | '8px' | '12px' | '16px' | '20px' | '24px' | '28px' | '9999px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
