import type { PageDocument } from "../types/page";

/** Thrown when an imported file is not a usable project document. The message
 * is user-facing (shown on the home screen). */
export class ProjectFileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProjectFileError";
  }
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null;
}

/** Serialize a project for a `.json` backup download (pretty-printed). */
export function serializeProject(doc: PageDocument): string {
  return JSON.stringify(doc, null, 2);
}

/**
 * Parse and shape-check a project `.json` file. Validates only the structural
 * invariants the app relies on (rootId resolves into nodes, meta.name exists);
 * missing per-node fields are backfilled later by the store's normalizeDocument.
 * Throws ProjectFileError with a user-facing message on any problem.
 */
export function parseProject(raw: string): PageDocument {
  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch {
    throw new ProjectFileError("JSON을 읽을 수 없습니다. 올바른 프로젝트 파일인지 확인하세요.");
  }
  if (!isRecord(data)) {
    throw new ProjectFileError("프로젝트 형식이 아닙니다.");
  }
  const { rootId, nodes, meta } = data;
  if (typeof rootId !== "string" || !isRecord(nodes) || !isRecord(meta)) {
    throw new ProjectFileError("프로젝트 구조가 올바르지 않습니다 (rootId·nodes·meta 필요).");
  }
  if (!(rootId in nodes)) {
    throw new ProjectFileError("rootId가 nodes 안에 존재하지 않습니다.");
  }
  if (typeof meta.name !== "string") {
    throw new ProjectFileError("meta.name이 없습니다.");
  }
  // Per-node shape check: the canvas relies on these (NodeView maps children,
  // getComponentDef keys on type). Missing frames are backfilled on load, but a
  // non-array `children` or missing `type` would crash the editor, so reject.
  for (const [nodeId, node] of Object.entries(nodes)) {
    if (!isRecord(node)) {
      throw new ProjectFileError(`노드 "${nodeId}" 형식이 올바르지 않습니다.`);
    }
    if (typeof node.type !== "string") {
      throw new ProjectFileError(`노드 "${nodeId}"에 type이 없습니다.`);
    }
    if (!Array.isArray(node.children)) {
      throw new ProjectFileError(`노드 "${nodeId}"의 children이 배열이 아닙니다.`);
    }
  }
  return data as unknown as PageDocument;
}

/**
 * Make a parsed document safe to add as a NEW project: assign a fresh id so an
 * import can never overwrite an existing project, and pin the schema version.
 * The thumbnail and updatedAt are regenerated by the storage layer on save.
 *
 * Node ids (and rootId) are kept as-is: projects live in separate localStorage
 * keys and are never co-mingled, so intra-tree ids only need to be unique within
 * the document — which the source already guarantees.
 */
export function prepareImport(doc: PageDocument): PageDocument {
  return { ...doc, id: crypto.randomUUID(), version: 1 };
}
